# Generated by Django 3.2.5 on 2021-07-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_voucher_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='code',
        ),
    ]
