# Generated by Django 3.2.5 on 2021-07-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_promotion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='have_discount',
            field=models.BooleanField(default=False),
        ),
    ]
