# Generated by Django 3.2.5 on 2021-07-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_promotion_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Frmale', 'Frmale')], max_length=10, null=True),
        ),
    ]
