# Generated by Django 3.2.5 on 2021-07-14 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(10)]),
        ),
    ]
