# Generated by Django 3.2.2 on 2021-08-09 18:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='references',
            new_name='payment_policy',
        ),
        migrations.AddField(
            model_name='setting',
            name='privacy_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='return_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='shipping_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='warranty_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
