# Generated by Django 3.2.5 on 2021-07-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_promotion_discount'),
        ('order', '0003_order_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promotion',
        ),
        migrations.AddField(
            model_name='order',
            name='total_after_used_voucher',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.voucher'),
        ),
    ]
